services:
  client:
    build: ./client-workshop1
    ports:
      - 4321:4321
  api:
    build: ./API-Workshop1
    ports:
      - 3000:3000
    env_file:
        - ./API-Workshop1/.env

